(function () {
  "use strict";
  var state = { client:null,session:null,data:null,selectedStudent:null,studentTimer:null,toastTimer:null };
  function el(id){return document.getElementById(id)}
  function all(q,r){return Array.prototype.slice.call((r||document).querySelectorAll(q))}
  function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
  function title(v){return String(v||"").replace(/_/g," ").replace(/\b\w/g,function(m){return m.toUpperCase()})}
  function today(){var d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)}
  function addDays(iso,n){var d=new Date(iso+"T12:00:00");d.setDate(d.getDate()+Number(n||0));return d.toISOString().slice(0,10)}
  function when(v){if(!v)return "Not recorded";var d=new Date(v);return isNaN(d.getTime())?String(v):d.toLocaleString()}
  function date(v){if(!v)return "Not set";var d=new Date(String(v).slice(0,10)+"T12:00:00");return isNaN(d.getTime())?String(v):d.toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})}
  function actor(){var v=String(el("actor-name").value||"").trim();if(!v){el("actor-name").focus();throw new Error("Enter your name before recording library work.")}localStorage.setItem("amfcc_library_actor",v);return v}
  function toast(message,error){clearTimeout(state.toastTimer);var b=el("toast");b.textContent=message;b.classList.toggle("error",!!error);b.hidden=false;state.toastTimer=setTimeout(function(){b.hidden=true},error?6500:3500)}
  function busy(form,on,label){var b=form.querySelector("button[type=submit]");if(!b)return;if(on){b.dataset.label=b.textContent;b.textContent=label||"Working...";b.disabled=true}else{b.textContent=b.dataset.label||b.textContent;b.disabled=false}}
  async function rpc(name,args){el("connection-state").textContent="Working";el("connection-state").className="pill neutral";var r=await state.client.rpc(name,args||{});if(r.error)throw r.error;if(r.data&&["unauthorized","locked"].indexOf(r.data.status)>=0&&name!=="library_login"){signOut(false);throw new Error(r.data.message||"Your library session has ended.")}el("connection-state").textContent="Connected";el("connection-state").className="pill green";return r.data}
  function storeSession(s){state.session=s;sessionStorage.setItem("amfcc_library_session",JSON.stringify(s))}
  function restoreSession(){try{var r=sessionStorage.getItem("amfcc_library_session");if(!r)return false;state.session=JSON.parse(r);return !!state.session.session_token}catch(e){sessionStorage.removeItem("amfcc_library_session");return false}}
  function showLogin(){el("login-screen").hidden=false;el("public-catalogue").hidden=true;el("app-shell").hidden=true;el("login-pin").value=""}
  function showApp(){el("login-screen").hidden=true;el("public-catalogue").hidden=true;el("app-shell").hidden=false}
  async function signOut(server){if(server!==false&&state.session){try{await rpc("library_logout",{p_session_token:state.session.session_token})}catch(e){}}state.session=null;state.data=null;sessionStorage.removeItem("amfcc_library_session");showLogin()}
  function switchView(view){all(".view").forEach(function(n){n.classList.toggle("active",n.id==="view-"+view)});all("#main-nav button").forEach(function(n){n.classList.toggle("active",n.dataset.view===view)})}
  async function command(action,payload){payload=payload||{};payload.actor_name=actor();var r=await rpc("library_command",{p_session_token:state.session.session_token,p_action:action,p_payload:payload});if(!r||r.status!=="success")throw new Error(r&&r.message||"The library action could not be completed.");return r}
  function setDefaultDue(){var days=state.data&&state.data.settings?Number(state.data.settings.loan_days||14):14;el("checkout-due").value=addDays(today(),days)}

  function renderSummary(){var s=state.data.summary||{},cards=[[s.titles||0,"Catalogue titles"],[s.copies||0,"Physical copies"],[s.available||0,"Available"],[s.active_loans||0,"Active loans"],[s.overdue||0,"Overdue"]];el("summary-cards").innerHTML=cards.map(function(c,i){return '<article class="summary-card '+(i===4&&Number(c[0])?"alert":"")+'"><strong>'+esc(c[0])+'</strong><span>'+esc(c[1])+'</span></article>'}).join("")}
  function copyPills(t){return '<span class="mini-pill available">'+Number(t.available_count||0)+' available</span><span class="mini-pill">'+Number(t.copy_count||0)+' copies</span>'}
  function renderCatalogue(){var q=String(el("catalog-search").value||"").trim().toLowerCase(),filter=el("catalog-filter").value;var items=(state.data.titles||[]).filter(function(t){var hay=[t.title,t.subtitle,t.author,t.isbn,t.category,t.shelf_location].join(" ").toLowerCase();if(q&&hay.indexOf(q)<0)return false;if(filter==="available"&&!Number(t.available_count))return false;if(filter==="on_loan"&&!Number(t.on_loan_count))return false;if(filter==="no_copies"&&Number(t.copy_count))return false;return true});var box=el("catalog-list");box.classList.toggle("empty-state",!items.length);box.innerHTML=items.length?items.map(function(t){var copies=(t.copies||[]).map(function(c){return '<div class="copy-row"><span><strong>'+esc(c.barcode)+'</strong><br><small>'+esc(c.accession_number||"No accession number")+'</small></span><span class="mini-pill '+esc(c.status)+'">'+esc(title(c.status))+'</span></div>'}).join("");return '<article class="catalog-card"><div><h3>'+esc(t.title)+'</h3><p>'+esc(t.author||"Author not entered")+(t.shelf_location?' · Shelf '+esc(t.shelf_location):'')+'</p></div><div class="catalog-meta">'+copyPills(t)+'</div>'+(copies?'<div class="copy-list">'+copies+'</div>':'<p class="muted">No physical copies entered.</p>')+'<div class="card-actions"><button class="button quiet edit-title" data-id="'+t.id+'" type="button">Edit title</button><button class="button secondary add-copy" data-id="'+t.id+'" type="button">Add copy</button></div></article>'}).join(""):"No catalogue titles match this view.";all(".edit-title",box).forEach(function(b){b.onclick=function(){editTitle(b.dataset.id)}});all(".add-copy",box).forEach(function(b){b.onclick=function(){openCopy(b.dataset.id)}})}
  function loanCard(l){return '<article class="loan-card '+(l.overdue?"overdue":"")+'"><div><h3>'+esc(l.title)+'</h3><p><strong>'+esc(l.borrower_name)+'</strong>'+(l.borrower_registration_number?' · '+esc(l.borrower_registration_number):' · Staff')+'</p><p>Barcode '+esc(l.barcode)+' · Due '+esc(date(l.due_date))+(l.overdue?' · '+esc(l.days_overdue)+' days overdue':'')+'</p></div><div class="loan-actions">'+(l.overdue?'<span class="mini-pill overdue">Overdue</span>':'<span class="mini-pill available">Active</span>')+'<button class="button quiet renew-loan" data-id="'+l.id+'" type="button">Renew</button><button class="button secondary return-loan" data-barcode="'+esc(l.barcode)+'" type="button">Return</button></div></article>'}
  function bindLoanActions(root){all(".renew-loan",root).forEach(function(b){b.onclick=async function(){if(!window.confirm("Renew this loan using the current standard loan period?"))return;try{var r=await command("renew",{loan_id:b.dataset.id});await load(false);toast("Loan renewed to "+date(r.due_date)+".")}catch(e){toast(e.message,true)}}});all(".return-loan",root).forEach(function(b){b.onclick=function(){el("return-barcode").value=b.dataset.barcode;switchView("circulation");el("return-barcode").focus()}})}
  function renderLoans(){var loans=state.data.active_loans||[],q=String(el("loan-search").value||"").trim().toLowerCase(),f=el("loan-filter").value;var soon=addDays(today(),3);var filtered=loans.filter(function(l){var hay=[l.borrower_name,l.borrower_registration_number,l.title,l.author,l.barcode].join(" ").toLowerCase();if(q&&hay.indexOf(q)<0)return false;if(f==="overdue"&&!l.overdue)return false;if(f==="due_soon"&&(l.due_date<today()||l.due_date>soon))return false;return true});el("active-loans").classList.toggle("empty-state",!filtered.length);el("active-loans").innerHTML=filtered.length?filtered.map(loanCard).join(""):"No active loans match this view.";bindLoanActions(el("active-loans"));var overdue=loans.filter(function(l){return l.overdue});el("overdue-loans").classList.toggle("empty-state",!overdue.length);el("overdue-loans").innerHTML=overdue.length?overdue.map(loanCard).join(""):"No overdue loans.";bindLoanActions(el("overdue-loans"));var due=loans.slice(0,8);el("circulation-loans").innerHTML=due.length?due.map(loanCard).join(""):"No active loans yet.";bindLoanActions(el("circulation-loans"))}
  function renderSettings(){var s=state.data.settings||{};el("loan-days").value=s.loan_days==null?14:s.loan_days;el("max-loans").value=s.max_active_loans==null?3:s.max_active_loans;el("max-renewals").value=s.max_renewals==null?1:s.max_renewals;el("public-enabled").checked=s.public_catalog_enabled!==false;all(".admin-only").forEach(function(n){n.hidden=!state.data.can_manage_settings});el("role-pill").textContent=state.data.role_label||title(state.data.role)}
  function renderAll(){renderSummary();renderCatalogue();renderLoans();renderSettings();setDefaultDue()}
  async function load(message){var d=await rpc("library_bootstrap",{p_session_token:state.session.session_token});if(d.status!=="success")throw new Error(d.message||"Could not load the Library.");state.data=d;renderAll();if(message)toast(message)}

  function resetTitle(){el("title-form").reset();el("title-id").value="";el("title-form").hidden=true}
  function editTitle(id){var t=(state.data.titles||[]).find(function(x){return x.id===id});if(!t)return;el("title-id").value=t.id;el("title-name").value=t.title||"";el("title-subtitle").value=t.subtitle||"";el("title-author").value=t.author||"";el("title-isbn").value=t.isbn||"";el("title-publisher").value=t.publisher||"";el("title-year").value=t.publication_year||"";el("title-category").value=t.category||"";el("title-shelf").value=t.shelf_location||"";el("title-notes").value=t.notes||"";el("title-form").hidden=false;el("title-name").focus()}
  function openCopy(id){var t=(state.data.titles||[]).find(function(x){return x.id===id});if(!t)return;el("copy-form").reset();el("copy-title-id").value=t.id;el("copy-title-label").textContent=t.title+(t.author?" by "+t.author:"");el("copy-modal").hidden=false;setTimeout(function(){el("copy-barcode").focus()},40)}
  function renderStudentResults(items){var box=el("student-results");box.hidden=!items.length;box.innerHTML=items.map(function(s){return '<div class="search-result"><span><strong>'+esc(s.full_name)+'</strong><br><small>'+esc(s.registration_number)+'</small></span><button class="button quiet choose-student" data-id="'+esc(s.id)+'" type="button">Choose</button></div>'}).join("");all(".choose-student",box).forEach(function(b){b.onclick=function(){state.selectedStudent=items.find(function(s){return s.id===b.dataset.id});el("selected-student").textContent=state.selectedStudent.full_name+" · "+state.selectedStudent.registration_number;el("selected-student").classList.add("ready");box.hidden=true;el("checkout-barcode").focus()}})}
  function csv(name,rows){if(!rows.length)return toast("There are no rows to export.",true);var keys=Object.keys(rows[0]),quote=function(v){if(v==null)return '""';return '"'+String(v).replace(/"/g,'""')+'"'};var body=[keys.map(quote).join(",")].concat(rows.map(function(r){return keys.map(function(k){return quote(r[k])}).join(",")})).join("\r\n");var blob=new Blob(["\ufeff"+body],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url)},1000)}
  async function publicSearch(){var r=await state.client.rpc("library_public_catalog",{p_query:String(el("public-search").value||"").trim()});if(r.error)throw r.error;var d=r.data,box=el("public-results");if(d.status!=="success"){box.textContent=d.message||"Catalogue unavailable.";return}var items=d.titles||[];box.classList.toggle("empty-state",!items.length);box.innerHTML=items.length?items.map(function(t){return '<article class="catalog-card"><h3>'+esc(t.title)+'</h3><p>'+esc(t.author||"Author not entered")+'</p><div class="catalog-meta"><span class="mini-pill available">'+esc(t.available_count)+' available</span><span class="mini-pill">Shelf '+esc(t.shelf_location||"not entered")+'</span></div></article>'}).join(""):"No books match that search."}

  function bind(){
    el("login-form").addEventListener("submit",async function(e){e.preventDefault();busy(e.currentTarget,true,"Opening...");el("login-message").hidden=true;try{var r=await rpc("library_login",{p_role:el("login-role").value,p_pin:el("login-pin").value.trim()});if(r.status!=="success")throw new Error(r.message||"Incorrect PIN.");storeSession(r);showApp();await load(false);toast("Library opened.")}catch(x){el("login-message").textContent=x.message||"Login failed.";el("login-message").className="form-message error";el("login-message").hidden=false}finally{busy(e.currentTarget,false)}});
    el("logout").onclick=function(){signOut(true)};el("refresh").onclick=function(){load("Library refreshed.").catch(function(e){toast(e.message,true)})};
    all("#main-nav button,.jump-view").forEach(function(b){b.onclick=function(){switchView(b.dataset.view)}});
    el("borrower-type").onchange=function(){var staff=this.value==="staff";el("student-search-field").hidden=staff;el("selected-student").hidden=staff;el("staff-name-field").hidden=!staff};
    el("student-search").oninput=function(){clearTimeout(state.studentTimer);var q=this.value.trim();if(q.length<2){el("student-results").hidden=true;return}state.studentTimer=setTimeout(async function(){try{var r=await rpc("library_search_students",{p_session_token:state.session.session_token,p_query:q});renderStudentResults(r.students||[])}catch(e){toast(e.message,true)}},250)};
    el("checkout-form").onsubmit=async function(e){e.preventDefault();busy(e.currentTarget,true,"Issuing...");try{var staff=el("borrower-type").value==="staff",payload={barcode:el("checkout-barcode").value.trim(),due_date:el("checkout-due").value||null,notes:el("checkout-notes").value.trim()};if(staff)payload.borrower_name=el("staff-borrower-name").value.trim();else{if(!state.selectedStudent)throw new Error("Choose a student first.");payload.registration_number=state.selectedStudent.registration_number}var r=await command(staff?"checkout_staff":"checkout",payload);e.currentTarget.reset();state.selectedStudent=null;el("selected-student").textContent="No student selected.";el("selected-student").classList.remove("ready");el("student-search-field").hidden=false;el("selected-student").hidden=false;el("staff-name-field").hidden=true;await load(false);toast("Book issued to "+r.borrower_name+". Due "+date(r.due_date)+".")}catch(x){toast(x.message,true)}finally{busy(e.currentTarget,false)}};
    el("return-form").onsubmit=async function(e){e.preventDefault();busy(e.currentTarget,true,"Returning...");try{var r=await command("return",{barcode:el("return-barcode").value.trim(),return_status:el("return-status").value,condition_notes:el("return-condition").value.trim()});e.currentTarget.reset();await load(false);toast("Book returned from "+r.borrower_name+".")}catch(x){toast(x.message,true)}finally{busy(e.currentTarget,false)}};
    el("new-title").onclick=function(){resetTitle();el("title-form").hidden=false;el("title-name").focus()};el("cancel-title").onclick=resetTitle;
    el("title-form").onsubmit=async function(e){e.preventDefault();busy(e.currentTarget,true,"Saving...");try{await command("save_title",{id:el("title-id").value||null,title:el("title-name").value,subtitle:el("title-subtitle").value,author:el("title-author").value,isbn:el("title-isbn").value,publisher:el("title-publisher").value,publication_year:el("title-year").value,category:el("title-category").value,shelf_location:el("title-shelf").value,notes:el("title-notes").value});resetTitle();await load(false);toast("Catalogue title saved.")}catch(x){toast(x.message,true)}finally{busy(e.currentTarget,false)}};
    el("copy-form").onsubmit=async function(e){e.preventDefault();busy(e.currentTarget,true,"Adding...");try{await command("add_copy",{title_id:el("copy-title-id").value,barcode:el("copy-barcode").value,accession_number:el("copy-accession").value,acquired_on:el("copy-acquired").value,condition_notes:el("copy-condition").value});el("copy-modal").hidden=true;await load(false);toast("Physical copy added.")}catch(x){toast(x.message,true)}finally{busy(e.currentTarget,false)}};
    el("close-copy").onclick=function(){el("copy-modal").hidden=true};el("copy-modal").onclick=function(e){if(e.target===el("copy-modal"))el("copy-modal").hidden=true};
    el("catalog-search").oninput=renderCatalogue;el("catalog-filter").onchange=renderCatalogue;el("loan-search").oninput=renderLoans;el("loan-filter").onchange=renderLoans;
    el("settings-form").onsubmit=async function(e){e.preventDefault();busy(e.currentTarget,true,"Saving...");try{var settings=[["loan_days",Number(el("loan-days").value)],["max_active_loans",Number(el("max-loans").value)],["max_renewals",Number(el("max-renewals").value)],["public_catalog_enabled",el("public-enabled").checked]];for(var i=0;i<settings.length;i++)await command("save_setting",{setting_key:settings[i][0],setting_value:settings[i][1]});await load(false);toast("Library rules saved.")}catch(x){toast(x.message,true)}finally{busy(e.currentTarget,false)}};
    el("export-catalogue").onclick=function(){var rows=[];(state.data.titles||[]).forEach(function(t){(t.copies||[]).forEach(function(c){rows.push({Title:t.title,Author:t.author||"",ISBN:t.isbn||"",Category:t.category||"",Shelf:t.shelf_location||"",Barcode:c.barcode,Accession:c.accession_number||"",Status:c.status,Condition:c.condition_notes||""})})});csv("amfcc-library-catalogue-"+today()+".csv",rows)};
    el("export-loans").onclick=function(){csv("amfcc-library-loans-"+today()+".csv",(state.data.recent_loans||[]).map(function(l){return {Borrower:l.borrower_name,Registration:l.borrower_registration_number||"Staff",Title:l.title,Author:l.author||"",Barcode:l.barcode,Borrowed:l.borrowed_at,Due:l.due_date,Returned:l.returned_at||"",Renewals:l.renew_count,IssuedBy:l.issued_by_name,ReturnedBy:l.returned_by_name||""}}))};
    el("export-overdue").onclick=function(){csv("amfcc-library-overdue-"+today()+".csv",(state.data.active_loans||[]).filter(function(l){return l.overdue}).map(function(l){return {Borrower:l.borrower_name,Registration:l.borrower_registration_number||"Staff",Title:l.title,Barcode:l.barcode,Due:l.due_date,DaysOverdue:l.days_overdue,IssuedBy:l.issued_by_name}}))};
    el("browse-public").onclick=async function(){el("login-screen").hidden=true;el("public-catalogue").hidden=false;try{await publicSearch()}catch(e){toast(e.message,true)}};el("close-public").onclick=showLogin;el("public-search").oninput=function(){clearTimeout(state.studentTimer);state.studentTimer=setTimeout(function(){publicSearch().catch(function(e){toast(e.message,true)})},250)};
  }
  document.addEventListener("DOMContentLoaded",async function(){state.client=window.amfccDb;el("actor-name").value=localStorage.getItem("amfcc_library_actor")||"";bind();if(restoreSession()){showApp();try{await load(false)}catch(e){signOut(false);toast(e.message||"Sign in again.",true)}}else showLogin()});
})();
